### ISSUE TITLE
Not decoding in Rattlegram

### ISSUE THREAD

**Issue by programmin1** [aicodix/code#1]
I'm not sure if this is the spot to report this, but when I test your RIBBIT beta ("Rattlegram") listening to the audible SMS in your QSO Today video from this weekend, I only see "Decoder Status"
"Preamble failure"

When I try with two phones with it installed, I see:
Mode 14 - CFO 1450.00Hz
Decoding failed

I'm not sure what went wrong.
Where is the source code of Rattlegram and can I use it as a Linux app as well?

**Comment by xdsopl** [comment]
If you are interested in the modem used for Rattlegram, here you go:
https://github.com/aicodix/modem/tree/short

We have a Reddit community about the COFDMTV technology used in the modem:
https://www.reddit.com/r/COFDMTV/

And there is also the COFDMTV website on our homepage:
https://www.aicodix.de/cofdmtv/

Regarding your Decoding failures, it might be a problem with activated auto gain control and or noise cancellation on your phone and you need to play with the settings. Hopefully the manual for Assempix will help you figure some things out:
https://www.aicodix.de/cofdmtv/assempix/

The source code for the Android app Rattlegram will not be available for the moment.
